Add `noaddon` option
plone/cookiecutter-volto pull request #8
Opened 2024-04-03 07:45 UTC by sneridagh

This is for the use case of the upcoming image. We need no addon in there to have a "clean" Volto if the image alone is run for demo purposes.

2024-04-03 11:00 UTC, ericof requested changes
Left some comments about style, but I do have questions about having the whole noaddon option here. Let's talk a bit more

2024-04-03 11:00 UTC, ericof commented on volto_addon/cookiecutter.json
> +  "noaddon": false,
Please, also add the user friendly version under `__prompts__`

2024-04-03 11:00 UTC, ericof commented on volto_addon/hooks/post_gen_project.py
> +    if os.path.isfile(filepath):
Use pathlib.Path

2024-04-03 11:00 UTC, ericof commented on volto_addon/{{ cookiecutter.addon_name }}/package.json
> +    {% if not cookiecutter.noaddon -%}
Why not to use:
```
  "dependencies": {
    "@plone/volto": "workspace:*",
    "@plone/registry": "workspace:*"{%- if not cookiecutter.noaddon -%},
    "{{ cookiecutter.npm_package_name }}": "workspace:*"
    {%- endif %}
  },
```

2024-04-03 11:00 UTC, ericof commented on volto_addon/{{ cookiecutter.addon_name }}/volto.config.js
> +{% if not cookiecutter.noaddon -%}
Why not to use:
```
const addons = [{%- if not cookiecutter.noaddon -%}'{{ cookiecutter.npm_package_name }}'{%- endif -%}];
```

2024-04-05 06:50 UTC, sneridagh commented on volto_addon/cookiecutter.json
> +  "noaddon": false,
Done

2024-04-05 06:50 UTC, sneridagh commented on volto_addon/hooks/post_gen_project.py
> +    if os.path.isfile(filepath):
Done

2024-04-05 06:50 UTC, sneridagh commented on volto_addon/{{ cookiecutter.addon_name }}/package.json
> +    {% if not cookiecutter.noaddon -%}
Done

2024-04-05 06:50 UTC, sneridagh commented on volto_addon/{{ cookiecutter.addon_name }}/volto.config.js
> +{% if not cookiecutter.noaddon -%}
Done

2024-04-05 06:52 UTC, sneridagh commented
@ericof It's needed for the generation of the image without add-on. It can be even be a hidden feature. If not, when we generate the image, there will be always the default add-on in there.

2024-04-05 11:06 UTC, ericof commented
Naming is hard :-)
I like the idea of a hidden option that would control this, let me try to
implement it

On Fri, Apr 5, 2024, 03:52 Víctor Fernández de Alba <
***@***.***> wrote:

> @ericof <https://github.com/ericof> It's needed for the generation of the
> image without add-on. It can be even be a hidden feature. If not, when we
> generate the image, there will be always the default add-on in there.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/plone/cookiecutter-volto/pull/8#issuecomment-2039078958>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACKWXWBX2O3R5KAP7YNTYLY3ZC2VAVCNFSM6AAAAABFUYMTGWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMZZGA3TQOJVHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-04-16 15:37 UTC, sneridagh commented
Let's do this in the image stage, not having a public facing way to do this.

2024-04-16 15:37 UTC, closed without merging